#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEmailReminders
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="ULS_db1")]
	public partial class ulsdbDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsvc_appointment(svc_appointment instance);
    partial void Updatesvc_appointment(svc_appointment instance);
    partial void Deletesvc_appointment(svc_appointment instance);
    partial void Insertsvc_contact(svc_contact instance);
    partial void Updatesvc_contact(svc_contact instance);
    partial void Deletesvc_contact(svc_contact instance);
    partial void Insertemployee(employee instance);
    partial void Updateemployee(employee instance);
    partial void Deleteemployee(employee instance);
    partial void InsertempQual(empQual instance);
    partial void UpdateempQual(empQual instance);
    partial void DeleteempQual(empQual instance);
    partial void Insertqual_notification(qual_notification instance);
    partial void Updatequal_notification(qual_notification instance);
    partial void Deletequal_notification(qual_notification instance);
    partial void Insertqualification(qualification instance);
    partial void Updatequalification(qualification instance);
    partial void Deletequalification(qualification instance);
    #endregion
		
		public ulsdbDataContextDataContext() : 
				base(global::ServiceEmailReminders.Properties.Settings.Default.ULS_db1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ulsdbDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ulsdbDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ulsdbDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ulsdbDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<svc_appointment> svc_appointments
		{
			get
			{
				return this.GetTable<svc_appointment>();
			}
		}
		
		public System.Data.Linq.Table<svc_contact> svc_contacts
		{
			get
			{
				return this.GetTable<svc_contact>();
			}
		}
		
		public System.Data.Linq.Table<employee> employees
		{
			get
			{
				return this.GetTable<employee>();
			}
		}
		
		public System.Data.Linq.Table<empQual> empQuals
		{
			get
			{
				return this.GetTable<empQual>();
			}
		}
		
		public System.Data.Linq.Table<qual_notification> qual_notifications
		{
			get
			{
				return this.GetTable<qual_notification>();
			}
		}
		
		public System.Data.Linq.Table<qualification> qualifications
		{
			get
			{
				return this.GetTable<qualification>();
			}
		}
	}
	
	[Table(Name="dbo.svc_appointments")]
	public partial class svc_appointment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _svc_id;
		
		private System.DateTime _svc_date;
		
		private string _last_name;
		
		private string _first_name;
		
		private string _street_address;
		
		private string _city;
		
		private string _state;
		
		private string _zip;
		
		private string _home_phone;
		
		private string _other_phone;
		
		private string _email;
		
		private int _crew;
		
		private System.Nullable<bool> _reschedule;
		
		private string _comments;
		
		private int _foreman_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsvc_idChanging(int value);
    partial void Onsvc_idChanged();
    partial void Onsvc_dateChanging(System.DateTime value);
    partial void Onsvc_dateChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onstreet_addressChanging(string value);
    partial void Onstreet_addressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void Onhome_phoneChanging(string value);
    partial void Onhome_phoneChanged();
    partial void Onother_phoneChanging(string value);
    partial void Onother_phoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncrewChanging(int value);
    partial void OncrewChanged();
    partial void OnrescheduleChanging(System.Nullable<bool> value);
    partial void OnrescheduleChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void Onforeman_idChanging(int value);
    partial void Onforeman_idChanged();
    #endregion
		
		public svc_appointment()
		{
			OnCreated();
		}
		
		[Column(Storage="_svc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int svc_id
		{
			get
			{
				return this._svc_id;
			}
			set
			{
				if ((this._svc_id != value))
				{
					this.Onsvc_idChanging(value);
					this.SendPropertyChanging();
					this._svc_id = value;
					this.SendPropertyChanged("svc_id");
					this.Onsvc_idChanged();
				}
			}
		}
		
		[Column(Storage="_svc_date", DbType="DateTime NOT NULL")]
		public System.DateTime svc_date
		{
			get
			{
				return this._svc_date;
			}
			set
			{
				if ((this._svc_date != value))
				{
					this.Onsvc_dateChanging(value);
					this.SendPropertyChanging();
					this._svc_date = value;
					this.SendPropertyChanged("svc_date");
					this.Onsvc_dateChanged();
				}
			}
		}
		
		[Column(Storage="_last_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[Column(Storage="_first_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[Column(Storage="_street_address", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string street_address
		{
			get
			{
				return this._street_address;
			}
			set
			{
				if ((this._street_address != value))
				{
					this.Onstreet_addressChanging(value);
					this.SendPropertyChanging();
					this._street_address = value;
					this.SendPropertyChanged("street_address");
					this.Onstreet_addressChanged();
				}
			}
		}
		
		[Column(Storage="_city", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[Column(Storage="_state", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[Column(Storage="_zip", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[Column(Storage="_home_phone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string home_phone
		{
			get
			{
				return this._home_phone;
			}
			set
			{
				if ((this._home_phone != value))
				{
					this.Onhome_phoneChanging(value);
					this.SendPropertyChanging();
					this._home_phone = value;
					this.SendPropertyChanged("home_phone");
					this.Onhome_phoneChanged();
				}
			}
		}
		
		[Column(Storage="_other_phone", DbType="VarChar(20)")]
		public string other_phone
		{
			get
			{
				return this._other_phone;
			}
			set
			{
				if ((this._other_phone != value))
				{
					this.Onother_phoneChanging(value);
					this.SendPropertyChanging();
					this._other_phone = value;
					this.SendPropertyChanged("other_phone");
					this.Onother_phoneChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_crew", DbType="Int NOT NULL")]
		public int crew
		{
			get
			{
				return this._crew;
			}
			set
			{
				if ((this._crew != value))
				{
					this.OncrewChanging(value);
					this.SendPropertyChanging();
					this._crew = value;
					this.SendPropertyChanged("crew");
					this.OncrewChanged();
				}
			}
		}
		
		[Column(Storage="_reschedule", DbType="Bit")]
		public System.Nullable<bool> reschedule
		{
			get
			{
				return this._reschedule;
			}
			set
			{
				if ((this._reschedule != value))
				{
					this.OnrescheduleChanging(value);
					this.SendPropertyChanging();
					this._reschedule = value;
					this.SendPropertyChanged("reschedule");
					this.OnrescheduleChanged();
				}
			}
		}
		
		[Column(Storage="_comments", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[Column(Storage="_foreman_id", DbType="Int NOT NULL")]
		public int foreman_id
		{
			get
			{
				return this._foreman_id;
			}
			set
			{
				if ((this._foreman_id != value))
				{
					this.Onforeman_idChanging(value);
					this.SendPropertyChanging();
					this._foreman_id = value;
					this.SendPropertyChanged("foreman_id");
					this.Onforeman_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.svc_contact")]
	public partial class svc_contact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _contact_id;
		
		private string _contact_name;
		
		private string _contact_number;
		
		private string _contact_email;
		
		private string _notify1_email;
		
		private string _notify2_email;
		
		private string _notify3_email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncontact_idChanging(int value);
    partial void Oncontact_idChanged();
    partial void Oncontact_nameChanging(string value);
    partial void Oncontact_nameChanged();
    partial void Oncontact_numberChanging(string value);
    partial void Oncontact_numberChanged();
    partial void Oncontact_emailChanging(string value);
    partial void Oncontact_emailChanged();
    partial void Onnotify1_emailChanging(string value);
    partial void Onnotify1_emailChanged();
    partial void Onnotify2_emailChanging(string value);
    partial void Onnotify2_emailChanged();
    partial void Onnotify3_emailChanging(string value);
    partial void Onnotify3_emailChanged();
    #endregion
		
		public svc_contact()
		{
			OnCreated();
		}
		
		[Column(Storage="_contact_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int contact_id
		{
			get
			{
				return this._contact_id;
			}
			set
			{
				if ((this._contact_id != value))
				{
					this.Oncontact_idChanging(value);
					this.SendPropertyChanging();
					this._contact_id = value;
					this.SendPropertyChanged("contact_id");
					this.Oncontact_idChanged();
				}
			}
		}
		
		[Column(Storage="_contact_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string contact_name
		{
			get
			{
				return this._contact_name;
			}
			set
			{
				if ((this._contact_name != value))
				{
					this.Oncontact_nameChanging(value);
					this.SendPropertyChanging();
					this._contact_name = value;
					this.SendPropertyChanged("contact_name");
					this.Oncontact_nameChanged();
				}
			}
		}
		
		[Column(Storage="_contact_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string contact_number
		{
			get
			{
				return this._contact_number;
			}
			set
			{
				if ((this._contact_number != value))
				{
					this.Oncontact_numberChanging(value);
					this.SendPropertyChanging();
					this._contact_number = value;
					this.SendPropertyChanged("contact_number");
					this.Oncontact_numberChanged();
				}
			}
		}
		
		[Column(Storage="_contact_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string contact_email
		{
			get
			{
				return this._contact_email;
			}
			set
			{
				if ((this._contact_email != value))
				{
					this.Oncontact_emailChanging(value);
					this.SendPropertyChanging();
					this._contact_email = value;
					this.SendPropertyChanged("contact_email");
					this.Oncontact_emailChanged();
				}
			}
		}
		
		[Column(Storage="_notify1_email", DbType="VarChar(50)")]
		public string notify1_email
		{
			get
			{
				return this._notify1_email;
			}
			set
			{
				if ((this._notify1_email != value))
				{
					this.Onnotify1_emailChanging(value);
					this.SendPropertyChanging();
					this._notify1_email = value;
					this.SendPropertyChanged("notify1_email");
					this.Onnotify1_emailChanged();
				}
			}
		}
		
		[Column(Storage="_notify2_email", DbType="VarChar(50)")]
		public string notify2_email
		{
			get
			{
				return this._notify2_email;
			}
			set
			{
				if ((this._notify2_email != value))
				{
					this.Onnotify2_emailChanging(value);
					this.SendPropertyChanging();
					this._notify2_email = value;
					this.SendPropertyChanged("notify2_email");
					this.Onnotify2_emailChanged();
				}
			}
		}
		
		[Column(Storage="_notify3_email", DbType="VarChar(50)")]
		public string notify3_email
		{
			get
			{
				return this._notify3_email;
			}
			set
			{
				if ((this._notify3_email != value))
				{
					this.Onnotify3_emailChanging(value);
					this.SendPropertyChanging();
					this._notify3_email = value;
					this.SendPropertyChanged("notify3_email");
					this.Onnotify3_emailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.employee")]
	public partial class employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _employeeID;
		
		private string _empId;
		
		private string _lname;
		
		private string _fname;
		
		private string _mname;
		
		private string _suffix;
		
		private char _empStatus;
		
		private string _org;
		
		private string _oqId;
		
		private string _comment;
		
		private string _ssn;
		
		private string _address1;
		
		private string _address2;
		
		private string _city;
		
		private string _state;
		
		private string _zip;
		
		private string _email;
		
		private string _homephone;
		
		private string _cellphone;
		
		private System.Nullable<decimal> _payRate;
		
		private string _jobClass;
		
		private string _oparea;
		
		private System.Nullable<System.DateTime> _MVRcheckDt;
		
		private System.Nullable<System.DateTime> _CBGcheckDt;
		
		private System.Nullable<System.DateTime> _DandAcheckDt;
		
		private System.Nullable<char> _DandAresult;
		
		private System.Nullable<System.DateTime> _last_updt_dt;
		
		private string _last_updt_uid;
		
		private System.Nullable<System.DateTime> _birthDate;
		
		private string _DLnum;
		
		private string _DLstate;
		
		private System.Nullable<char> _DLclass;
		
		private System.Nullable<System.DateTime> _DLexpDate;
		
		private System.Nullable<System.DateTime> _medicalCardExpDt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemployeeIDChanging(int value);
    partial void OnemployeeIDChanged();
    partial void OnempIdChanging(string value);
    partial void OnempIdChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnmnameChanging(string value);
    partial void OnmnameChanged();
    partial void OnsuffixChanging(string value);
    partial void OnsuffixChanged();
    partial void OnempStatusChanging(char value);
    partial void OnempStatusChanged();
    partial void OnorgChanging(string value);
    partial void OnorgChanged();
    partial void OnoqIdChanging(string value);
    partial void OnoqIdChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnssnChanging(string value);
    partial void OnssnChanged();
    partial void Onaddress1Changing(string value);
    partial void Onaddress1Changed();
    partial void Onaddress2Changing(string value);
    partial void Onaddress2Changed();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnhomephoneChanging(string value);
    partial void OnhomephoneChanged();
    partial void OncellphoneChanging(string value);
    partial void OncellphoneChanged();
    partial void OnpayRateChanging(System.Nullable<decimal> value);
    partial void OnpayRateChanged();
    partial void OnjobClassChanging(string value);
    partial void OnjobClassChanged();
    partial void OnopareaChanging(string value);
    partial void OnopareaChanged();
    partial void OnMVRcheckDtChanging(System.Nullable<System.DateTime> value);
    partial void OnMVRcheckDtChanged();
    partial void OnCBGcheckDtChanging(System.Nullable<System.DateTime> value);
    partial void OnCBGcheckDtChanged();
    partial void OnDandAcheckDtChanging(System.Nullable<System.DateTime> value);
    partial void OnDandAcheckDtChanged();
    partial void OnDandAresultChanging(System.Nullable<char> value);
    partial void OnDandAresultChanged();
    partial void Onlast_updt_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_updt_dtChanged();
    partial void Onlast_updt_uidChanging(string value);
    partial void Onlast_updt_uidChanged();
    partial void OnbirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthDateChanged();
    partial void OnDLnumChanging(string value);
    partial void OnDLnumChanged();
    partial void OnDLstateChanging(string value);
    partial void OnDLstateChanged();
    partial void OnDLclassChanging(System.Nullable<char> value);
    partial void OnDLclassChanged();
    partial void OnDLexpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDLexpDateChanged();
    partial void OnmedicalCardExpDtChanging(System.Nullable<System.DateTime> value);
    partial void OnmedicalCardExpDtChanged();
    #endregion
		
		public employee()
		{
			OnCreated();
		}
		
		[Column(Storage="_employeeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int employeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				if ((this._employeeID != value))
				{
					this.OnemployeeIDChanging(value);
					this.SendPropertyChanging();
					this._employeeID = value;
					this.SendPropertyChanged("employeeID");
					this.OnemployeeIDChanged();
				}
			}
		}
		
		[Column(Storage="_empId", DbType="VarChar(15)")]
		public string empId
		{
			get
			{
				return this._empId;
			}
			set
			{
				if ((this._empId != value))
				{
					this.OnempIdChanging(value);
					this.SendPropertyChanging();
					this._empId = value;
					this.SendPropertyChanged("empId");
					this.OnempIdChanged();
				}
			}
		}
		
		[Column(Storage="_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lname
		{
			get
			{
				return this._lname;
			}
			set
			{
				if ((this._lname != value))
				{
					this.OnlnameChanging(value);
					this.SendPropertyChanging();
					this._lname = value;
					this.SendPropertyChanged("lname");
					this.OnlnameChanged();
				}
			}
		}
		
		[Column(Storage="_fname", DbType="VarChar(50)")]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this.OnfnameChanging(value);
					this.SendPropertyChanging();
					this._fname = value;
					this.SendPropertyChanged("fname");
					this.OnfnameChanged();
				}
			}
		}
		
		[Column(Storage="_mname", DbType="VarChar(50)")]
		public string mname
		{
			get
			{
				return this._mname;
			}
			set
			{
				if ((this._mname != value))
				{
					this.OnmnameChanging(value);
					this.SendPropertyChanging();
					this._mname = value;
					this.SendPropertyChanged("mname");
					this.OnmnameChanged();
				}
			}
		}
		
		[Column(Storage="_suffix", DbType="VarChar(10)")]
		public string suffix
		{
			get
			{
				return this._suffix;
			}
			set
			{
				if ((this._suffix != value))
				{
					this.OnsuffixChanging(value);
					this.SendPropertyChanging();
					this._suffix = value;
					this.SendPropertyChanged("suffix");
					this.OnsuffixChanged();
				}
			}
		}
		
		[Column(Storage="_empStatus", DbType="Char(1) NOT NULL")]
		public char empStatus
		{
			get
			{
				return this._empStatus;
			}
			set
			{
				if ((this._empStatus != value))
				{
					this.OnempStatusChanging(value);
					this.SendPropertyChanging();
					this._empStatus = value;
					this.SendPropertyChanged("empStatus");
					this.OnempStatusChanged();
				}
			}
		}
		
		[Column(Storage="_org", DbType="VarChar(10)")]
		public string org
		{
			get
			{
				return this._org;
			}
			set
			{
				if ((this._org != value))
				{
					this.OnorgChanging(value);
					this.SendPropertyChanging();
					this._org = value;
					this.SendPropertyChanged("org");
					this.OnorgChanged();
				}
			}
		}
		
		[Column(Storage="_oqId", DbType="VarChar(10)")]
		public string oqId
		{
			get
			{
				return this._oqId;
			}
			set
			{
				if ((this._oqId != value))
				{
					this.OnoqIdChanging(value);
					this.SendPropertyChanging();
					this._oqId = value;
					this.SendPropertyChanged("oqId");
					this.OnoqIdChanged();
				}
			}
		}
		
		[Column(Storage="_comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[Column(Storage="_ssn", DbType="VarChar(12)")]
		public string ssn
		{
			get
			{
				return this._ssn;
			}
			set
			{
				if ((this._ssn != value))
				{
					this.OnssnChanging(value);
					this.SendPropertyChanging();
					this._ssn = value;
					this.SendPropertyChanged("ssn");
					this.OnssnChanged();
				}
			}
		}
		
		[Column(Storage="_address1", DbType="VarChar(50)")]
		public string address1
		{
			get
			{
				return this._address1;
			}
			set
			{
				if ((this._address1 != value))
				{
					this.Onaddress1Changing(value);
					this.SendPropertyChanging();
					this._address1 = value;
					this.SendPropertyChanged("address1");
					this.Onaddress1Changed();
				}
			}
		}
		
		[Column(Storage="_address2", DbType="VarChar(50)")]
		public string address2
		{
			get
			{
				return this._address2;
			}
			set
			{
				if ((this._address2 != value))
				{
					this.Onaddress2Changing(value);
					this.SendPropertyChanging();
					this._address2 = value;
					this.SendPropertyChanged("address2");
					this.Onaddress2Changed();
				}
			}
		}
		
		[Column(Storage="_city", DbType="VarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[Column(Storage="_state", DbType="VarChar(2)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[Column(Storage="_zip", DbType="VarChar(10)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_homephone", DbType="VarChar(25)")]
		public string homephone
		{
			get
			{
				return this._homephone;
			}
			set
			{
				if ((this._homephone != value))
				{
					this.OnhomephoneChanging(value);
					this.SendPropertyChanging();
					this._homephone = value;
					this.SendPropertyChanged("homephone");
					this.OnhomephoneChanged();
				}
			}
		}
		
		[Column(Storage="_cellphone", DbType="VarChar(25)")]
		public string cellphone
		{
			get
			{
				return this._cellphone;
			}
			set
			{
				if ((this._cellphone != value))
				{
					this.OncellphoneChanging(value);
					this.SendPropertyChanging();
					this._cellphone = value;
					this.SendPropertyChanged("cellphone");
					this.OncellphoneChanged();
				}
			}
		}
		
		[Column(Storage="_payRate", DbType="Money")]
		public System.Nullable<decimal> payRate
		{
			get
			{
				return this._payRate;
			}
			set
			{
				if ((this._payRate != value))
				{
					this.OnpayRateChanging(value);
					this.SendPropertyChanging();
					this._payRate = value;
					this.SendPropertyChanged("payRate");
					this.OnpayRateChanged();
				}
			}
		}
		
		[Column(Storage="_jobClass", DbType="VarChar(10)")]
		public string jobClass
		{
			get
			{
				return this._jobClass;
			}
			set
			{
				if ((this._jobClass != value))
				{
					this.OnjobClassChanging(value);
					this.SendPropertyChanging();
					this._jobClass = value;
					this.SendPropertyChanged("jobClass");
					this.OnjobClassChanged();
				}
			}
		}
		
		[Column(Storage="_oparea", DbType="VarChar(25)")]
		public string oparea
		{
			get
			{
				return this._oparea;
			}
			set
			{
				if ((this._oparea != value))
				{
					this.OnopareaChanging(value);
					this.SendPropertyChanging();
					this._oparea = value;
					this.SendPropertyChanged("oparea");
					this.OnopareaChanged();
				}
			}
		}
		
		[Column(Storage="_MVRcheckDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> MVRcheckDt
		{
			get
			{
				return this._MVRcheckDt;
			}
			set
			{
				if ((this._MVRcheckDt != value))
				{
					this.OnMVRcheckDtChanging(value);
					this.SendPropertyChanging();
					this._MVRcheckDt = value;
					this.SendPropertyChanged("MVRcheckDt");
					this.OnMVRcheckDtChanged();
				}
			}
		}
		
		[Column(Storage="_CBGcheckDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CBGcheckDt
		{
			get
			{
				return this._CBGcheckDt;
			}
			set
			{
				if ((this._CBGcheckDt != value))
				{
					this.OnCBGcheckDtChanging(value);
					this.SendPropertyChanging();
					this._CBGcheckDt = value;
					this.SendPropertyChanged("CBGcheckDt");
					this.OnCBGcheckDtChanged();
				}
			}
		}
		
		[Column(Storage="_DandAcheckDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> DandAcheckDt
		{
			get
			{
				return this._DandAcheckDt;
			}
			set
			{
				if ((this._DandAcheckDt != value))
				{
					this.OnDandAcheckDtChanging(value);
					this.SendPropertyChanging();
					this._DandAcheckDt = value;
					this.SendPropertyChanged("DandAcheckDt");
					this.OnDandAcheckDtChanged();
				}
			}
		}
		
		[Column(Storage="_DandAresult", DbType="Char(1)")]
		public System.Nullable<char> DandAresult
		{
			get
			{
				return this._DandAresult;
			}
			set
			{
				if ((this._DandAresult != value))
				{
					this.OnDandAresultChanging(value);
					this.SendPropertyChanging();
					this._DandAresult = value;
					this.SendPropertyChanged("DandAresult");
					this.OnDandAresultChanged();
				}
			}
		}
		
		[Column(Storage="_last_updt_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_updt_dt
		{
			get
			{
				return this._last_updt_dt;
			}
			set
			{
				if ((this._last_updt_dt != value))
				{
					this.Onlast_updt_dtChanging(value);
					this.SendPropertyChanging();
					this._last_updt_dt = value;
					this.SendPropertyChanged("last_updt_dt");
					this.Onlast_updt_dtChanged();
				}
			}
		}
		
		[Column(Storage="_last_updt_uid", DbType="VarChar(25)")]
		public string last_updt_uid
		{
			get
			{
				return this._last_updt_uid;
			}
			set
			{
				if ((this._last_updt_uid != value))
				{
					this.Onlast_updt_uidChanging(value);
					this.SendPropertyChanging();
					this._last_updt_uid = value;
					this.SendPropertyChanged("last_updt_uid");
					this.Onlast_updt_uidChanged();
				}
			}
		}
		
		[Column(Storage="_birthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				if ((this._birthDate != value))
				{
					this.OnbirthDateChanging(value);
					this.SendPropertyChanging();
					this._birthDate = value;
					this.SendPropertyChanged("birthDate");
					this.OnbirthDateChanged();
				}
			}
		}
		
		[Column(Storage="_DLnum", DbType="VarChar(50)")]
		public string DLnum
		{
			get
			{
				return this._DLnum;
			}
			set
			{
				if ((this._DLnum != value))
				{
					this.OnDLnumChanging(value);
					this.SendPropertyChanging();
					this._DLnum = value;
					this.SendPropertyChanged("DLnum");
					this.OnDLnumChanged();
				}
			}
		}
		
		[Column(Storage="_DLstate", DbType="VarChar(2)")]
		public string DLstate
		{
			get
			{
				return this._DLstate;
			}
			set
			{
				if ((this._DLstate != value))
				{
					this.OnDLstateChanging(value);
					this.SendPropertyChanging();
					this._DLstate = value;
					this.SendPropertyChanged("DLstate");
					this.OnDLstateChanged();
				}
			}
		}
		
		[Column(Storage="_DLclass", DbType="Char(1)")]
		public System.Nullable<char> DLclass
		{
			get
			{
				return this._DLclass;
			}
			set
			{
				if ((this._DLclass != value))
				{
					this.OnDLclassChanging(value);
					this.SendPropertyChanging();
					this._DLclass = value;
					this.SendPropertyChanged("DLclass");
					this.OnDLclassChanged();
				}
			}
		}
		
		[Column(Storage="_DLexpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DLexpDate
		{
			get
			{
				return this._DLexpDate;
			}
			set
			{
				if ((this._DLexpDate != value))
				{
					this.OnDLexpDateChanging(value);
					this.SendPropertyChanging();
					this._DLexpDate = value;
					this.SendPropertyChanged("DLexpDate");
					this.OnDLexpDateChanged();
				}
			}
		}
		
		[Column(Storage="_medicalCardExpDt", DbType="DateTime")]
		public System.Nullable<System.DateTime> medicalCardExpDt
		{
			get
			{
				return this._medicalCardExpDt;
			}
			set
			{
				if ((this._medicalCardExpDt != value))
				{
					this.OnmedicalCardExpDtChanging(value);
					this.SendPropertyChanging();
					this._medicalCardExpDt = value;
					this.SendPropertyChanged("medicalCardExpDt");
					this.OnmedicalCardExpDtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.empQual")]
	public partial class empQual : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _employeeId;
		
		private string _empId;
		
		private string _qualId;
		
		private System.Nullable<System.DateTime> _qualDate;
		
		private System.Nullable<System.DateTime> _qualExpire;
		
		private string _evaluator;
		
		private string _qualCompany;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemployeeIdChanging(int value);
    partial void OnemployeeIdChanged();
    partial void OnempIdChanging(string value);
    partial void OnempIdChanged();
    partial void OnqualIdChanging(string value);
    partial void OnqualIdChanged();
    partial void OnqualDateChanging(System.Nullable<System.DateTime> value);
    partial void OnqualDateChanged();
    partial void OnqualExpireChanging(System.Nullable<System.DateTime> value);
    partial void OnqualExpireChanged();
    partial void OnevaluatorChanging(string value);
    partial void OnevaluatorChanged();
    partial void OnqualCompanyChanging(string value);
    partial void OnqualCompanyChanged();
    #endregion
		
		public empQual()
		{
			OnCreated();
		}
		
		[Column(Storage="_employeeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int employeeId
		{
			get
			{
				return this._employeeId;
			}
			set
			{
				if ((this._employeeId != value))
				{
					this.OnemployeeIdChanging(value);
					this.SendPropertyChanging();
					this._employeeId = value;
					this.SendPropertyChanged("employeeId");
					this.OnemployeeIdChanged();
				}
			}
		}
		
		[Column(Storage="_empId", DbType="VarChar(10)")]
		public string empId
		{
			get
			{
				return this._empId;
			}
			set
			{
				if ((this._empId != value))
				{
					this.OnempIdChanging(value);
					this.SendPropertyChanging();
					this._empId = value;
					this.SendPropertyChanged("empId");
					this.OnempIdChanged();
				}
			}
		}
		
		[Column(Storage="_qualId", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string qualId
		{
			get
			{
				return this._qualId;
			}
			set
			{
				if ((this._qualId != value))
				{
					this.OnqualIdChanging(value);
					this.SendPropertyChanging();
					this._qualId = value;
					this.SendPropertyChanged("qualId");
					this.OnqualIdChanged();
				}
			}
		}
		
		[Column(Storage="_qualDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> qualDate
		{
			get
			{
				return this._qualDate;
			}
			set
			{
				if ((this._qualDate != value))
				{
					this.OnqualDateChanging(value);
					this.SendPropertyChanging();
					this._qualDate = value;
					this.SendPropertyChanged("qualDate");
					this.OnqualDateChanged();
				}
			}
		}
		
		[Column(Storage="_qualExpire", DbType="DateTime")]
		public System.Nullable<System.DateTime> qualExpire
		{
			get
			{
				return this._qualExpire;
			}
			set
			{
				if ((this._qualExpire != value))
				{
					this.OnqualExpireChanging(value);
					this.SendPropertyChanging();
					this._qualExpire = value;
					this.SendPropertyChanged("qualExpire");
					this.OnqualExpireChanged();
				}
			}
		}
		
		[Column(Storage="_evaluator", DbType="VarChar(100)")]
		public string evaluator
		{
			get
			{
				return this._evaluator;
			}
			set
			{
				if ((this._evaluator != value))
				{
					this.OnevaluatorChanging(value);
					this.SendPropertyChanging();
					this._evaluator = value;
					this.SendPropertyChanged("evaluator");
					this.OnevaluatorChanged();
				}
			}
		}
		
		[Column(Storage="_qualCompany", DbType="VarChar(25)")]
		public string qualCompany
		{
			get
			{
				return this._qualCompany;
			}
			set
			{
				if ((this._qualCompany != value))
				{
					this.OnqualCompanyChanging(value);
					this.SendPropertyChanging();
					this._qualCompany = value;
					this.SendPropertyChanged("qualCompany");
					this.OnqualCompanyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.qual_notification")]
	public partial class qual_notification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public qual_notification()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.qualification")]
	public partial class qualification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _qualID;
		
		private string _qualDesc;
		
		private string _qualCompany;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnqualIDChanging(string value);
    partial void OnqualIDChanged();
    partial void OnqualDescChanging(string value);
    partial void OnqualDescChanged();
    partial void OnqualCompanyChanging(string value);
    partial void OnqualCompanyChanged();
    #endregion
		
		public qualification()
		{
			OnCreated();
		}
		
		[Column(Storage="_qualID", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string qualID
		{
			get
			{
				return this._qualID;
			}
			set
			{
				if ((this._qualID != value))
				{
					this.OnqualIDChanging(value);
					this.SendPropertyChanging();
					this._qualID = value;
					this.SendPropertyChanged("qualID");
					this.OnqualIDChanged();
				}
			}
		}
		
		[Column(Storage="_qualDesc", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string qualDesc
		{
			get
			{
				return this._qualDesc;
			}
			set
			{
				if ((this._qualDesc != value))
				{
					this.OnqualDescChanging(value);
					this.SendPropertyChanging();
					this._qualDesc = value;
					this.SendPropertyChanged("qualDesc");
					this.OnqualDescChanged();
				}
			}
		}
		
		[Column(Storage="_qualCompany", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string qualCompany
		{
			get
			{
				return this._qualCompany;
			}
			set
			{
				if ((this._qualCompany != value))
				{
					this.OnqualCompanyChanging(value);
					this.SendPropertyChanging();
					this._qualCompany = value;
					this.SendPropertyChanged("qualCompany");
					this.OnqualCompanyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
